### ISSUE TITLE
answer contains possibility not existing in code in HW2.3

### ISSUE THREAD

**Issue by jonashrem** [redislabs-training/ru102py#37]
See 
![image](https://user-images.githubusercontent.com/1112507/96296364-7a656d80-0fef-11eb-90fd-a4dacc8341d7.png)

One answer is suggesting `pipeline.set("a", "foo")` but this code is not existing in the code above (I assume it should be `client.set("a", "foo")`

**Comment by abrookins** [comment]
@jonashrem I missed this issue until now! Thanks for reporting -- I'll get that fixed.

**Comment by abrookins** [comment]
Fixed.
