### ISSUE TITLE
Add a screenshot of the running application to the README 

### ISSUE THREAD

**Issue by simonprickett** [redislabs-training/ru102py#62]
Update `README.md` to add a screenshot of the running application, showing the map view with the solar site markers on it. For this you will need to follow the instructions in the README to get the application running.  The code to generate the markers is stubbed out on the `master` branch in this repo as it's an exercise for the training course that this repo is part of.  To get the markers to draw so that you can take your screenshot, temporarily paste in the code from the `solutions` branch here: https://github.com/redislabs-training/ru102py/blob/dcdf3194ec3ad913aedb378156cb6e3e91b99da1/redisolar/dao/redis/site.py#L37

This is part of our participation in Hacktoberfest 2021.  Learn how to complete this issue here: https://developer.redis.com/hacktoberfest/

Need help or want to talk to us?  Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

**Comment by Jogius** [comment]
Hey, I'd like to work on this issue. Do you have any preference for the size of the screenshot, where it should be saved and to what part of the README.md file it should be added or may I make these choices myself?

**Comment by simonprickett** [comment]
> Hey, I'd like to work on this issue. Do you have any preference for the size of the screenshot, where it should be saved and to what part of the README.md file it should be added or may I make these choices myself?

Hi there I'll assign this one to you - something that fills the entire width would be nice and maybe right at the top before the "Setup"  section would be good.  Adding the image to the root folder in the repo works.  

Here's our Hacktoberfest guidelines, thanks for taking part!  https://developer.redis.com/hacktoberfest/
